### ISSUE TITLE
32-bit architecture support

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-forwarder#10]
The forwarder can currently run only on 64-bit machines.

As LMDB is used for the back-end, buffer file size is limited to 4 GB on 32-bit, but because the forwarder needs additional space to allow for fragmentation - stored data vs. footprint, and to provide adequate additional space when data is received while purging is in progress, the usable buffer space is less.

LMDB is a great storage format for this scenario because of its recovery-free design (vs. others using WAL which may require manual intervention to recover from time to time). That benefit aside, we probably want to use an alternative on 32-bit systems.

**Comment by bbrandt** [comment]
There's still 32-bit systems running out there?  :smile:

**Comment by nblumhardt** [comment]
Going to close this and see what we find in practice - I think there are probably higher-impact things to work on in this repository for now.
