### ISSUE TITLE
A shorter executable command name

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-forwarder#11]
Now that Seq Forwarder has assumed some interactive functionality, `seq-forwarder` feels like too much to type at the command-line.

A shorter name for the binary, for example `seqfw`, will be more comfortable to use as the number of interactive scenarios increases.

**Comment by nblumhardt** [comment]
This will be `seqcli.exe` or `seqclient.exe`.

**Comment by laurencee** [comment]
seqcli get my vote, it is afterall a command line interface.

**Comment by nblumhardt** [comment]
https://github.com/datalust/seqcli now exists, is slightly different in scope from the forwarder, but covers the command-line client functionality we'd considered adding here.
