### ISSUE TITLE
Can you chain seq-forwarders?

### ISSUE THREAD

**Issue by markstratman** [datalust/seq-forwarder#14]
We have a public server (A)  that talks to a server (B) in a DMZ which in turn talks to our SEQ server (C).  Can seq-fowarder forward from A to a seq-fowarder on B which in turn would forward it to C, our SEQ server?

**Comment by nblumhardt** [comment]
Hi Mark, yes - that's definitely the intention. If you hit any trouble along the way please shout :-)

Regards,
Nick
