### ISSUE TITLE
Support .NET Core, Linux, Docker

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-forwarder#21]
Meta-issue for a whole range of tasks. No fixed timeline, but started on this with #15 recently. Any and all help welcome, just add a comment to help coordinate efforts.

 - [ ] Port to .NET Core
   * Update NancyFx/self-host infrastructure
   * Move service management, installation and hosting code to a separate .NET Framework wrapper for Windows
    * New .NET Core binary build target
 - [ ] Linux
    * Build and potentially packaging for popular distro(s); probably Ubuntu 16.04/x86-64 for a start
 - [ ] Docker
    * Wrap all of the above up in a nice self-contained, configurable container

**Comment by npnelson** [comment]
Ubuntu 16.04 is a great choice, although it looks like you would only have to worry about x64. https://github.com/dotnet/core/blob/master/roadmap.md

I would also consider supporting a Windows Container running nanoserver

**Comment by andymac4182** [comment]
Thoughts on moving to ASP.NET Core from Nancy?
