### ISSUE TITLE
Buffer Folder Not Created By Installer

### ISSUE THREAD

**Issue by mason-mcglothlin** [datalust/seq-forwarder#34]
Using v1.0.69 installer to install for the first time on a machine.

Install SEQ Forwarder to "C:\Program Files\Seq Forwarder\"
Leave the option for "Install or start the SEQ Forwarder service on exit" checked.
Leave the Storage Path as "C:\ProgramData\Seq\Forwarder".
Enter a server URL and leave API key blank.

"There was a problem configuring the service; please refer to the output above"

> Installing service...
> Creating a new configuration file in C:\ProgramData\Seq\Forwarder\SeqForwarder.json...
> Granting the NT AUTHORITY\LocalService account rights to C:\ProgramData\Seq\Forwarder...
> Granting NT AUTHORITY\LocalService account rights to C:\ProgramData\Seq\Logs\...
> Adding URL reservation at http://+:15341/ for the Local Service account (may request UAC elevation)...
> 
> Running a transacted installation.
> 
> Beginning the Install phase of the installation.
> See the contents of the log file for the C:\Program Files\Seq Forwarder\seq-forwarder.exe assembly's progress.
> The file is located at "".
> Installing assembly 'C:\Program Files\Seq Forwarder\seq-forwarder.exe'.
> Affected parameters are:
>    assemblypath = C:\Program Files\Seq Forwarder\seq-forwarder.exe
>    showcallstack = 
>    logtoconsole = 
>    storage = "C:\ProgramData\Seq\Forwarder"
>    logfile = 
> Installing service Seq Forwarder...
> Service Seq Forwarder has been successfully installed.
> Creating EventLog source Seq Forwarder in log Application...
> 
> The Install phase completed successfully, and the Commit phase is beginning.
> See the contents of the log file for the C:\Program Files\Seq Forwarder\seq-forwarder.exe assembly's progress.
> The file is located at "".
> Committing assembly 'C:\Program Files\Seq Forwarder\seq-forwarder.exe'.
> Affected parameters are:
>    assemblypath = C:\Program Files\Seq Forwarder\seq-forwarder.exe
>    showcallstack = 
>    logtoconsole = 
>    storage = "C:\ProgramData\Seq\Forwarder"
>    logfile = 
> 
> The Commit phase completed successfully.
> 
> The transacted install has completed.
> Service installed successfully.
> Starting Seq Forwarder...
> Waiting up to 15 seconds for the service to start (currently: Stopped)...
> Time out has expired and the operation has not been completed.

Now for my workaround. I manually create a folder "C:\ProgramData\Seq\Forwarder\Buffer" and then start the service (successfully).

I was able to reproduce this issue on at least 10 different machines.

**Comment by nblumhardt** [comment]
Thanks for the report @mason-mcglothlin - shows a bit of a weakness in my testing strategy :-/

I've committed the fix; there should be a release out shortly.
