### ISSUE TITLE
Seq Forwarder v1.1.73 issues

### ISSUE THREAD

**Issue by astavria4** [datalust/seq-forwarder#41]
Hello,

I recently installed Seq Forwarder v1.1.73  on my local machine to test. When I first installed, the buffer directory was not created ( I had to manually create it myself). 

From reading previous posts, v1.0.69 supports API key forwarding. If I were to leave the API key section in the Seq Forwarder Configuration screen blank and instantiate the Logger as below, the error does not get to the Seq Server and I get this in the log: {"@t":"2018-12-04T15:12:16.3846093Z","@m":"The default buffer is empty and will be removed until more data is received","@i":"745bce03","SourceContext":"Seq.Forwarder.Multiplexing.ActiveLogBufferMap"}
```

Log.Logger = new LoggerConfiguration()
                .WriteTo.Seq("http://localhost:15341",_logLevel, apiKey: _apiKey, compact: true)
                .CreateLogger();

            Log.Error(exception,"");

            Log.CloseAndFlush();
```

Am I doing something wrong here?

**Comment by nblumhardt** [comment]
Hi, and thanks for checking this out. Your sample looks fine, although it's unusual to see a `""` empty message in there.

Does the same code send events successfully if no API key is used, and it's instead set in the forwarder configuration?

Best regards,
Nick

**Comment by astavria4** [comment]
Hi Nick,

You are correct. The same code sends  events successfully if no API key is used, and it's instead set in the forwarder configuration.

Thanks,
Alex
________________________________

**Comment by nblumhardt** [comment]
Thanks for the follow-up. We'll take a closer look and see what other failure paths are possible, here.

**Comment by astavria4** [comment]
Thanks. We would like to use Seq Forwarder for all of our applications but we need to have unique api keys per app.

Thanks,
Alex

________________________________

**Comment by astavria** [comment]
per your suggestion, removing compact: true

from Log.Logger = new LoggerConfiguration()
                .WriteTo.Seq("http://localhost:15341",_logLevel, apiKey: _apiKey, compact: true)
                .CreateLogger(); 

fixed this issue. 

Thanks for working with me!

**Comment by nblumhardt** [comment]
:tada:
