### ISSUE TITLE
Environment variable-based configuration

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-forwarder#55]
Currently settings from `SeqForwarder.json` don't have environment variable counterparts (the way that Seq settings do). For use cases like Docker packaging, this would be really convenient.

**Comment by coderpatros** [comment]
@nblumhardt would you take a PR for this? @stevekirks

**Comment by nblumhardt** [comment]
Hi @coderpatros - Yes, I think it would be a great PR, if you are keen! 👍 

Quick brain dump: there are a couple of gotchas, like, when we read the config to `run` the forwarder, we want environment variables merged in, but when the `config` command is used to read/describe/write the config file, the env vars should (probably) be ignored.

We'd also plan to keep it quite close to how Seq does configuration; e.g. the `output.serverUrl` config setting would be mapped to (e.g.) `FORWARDER_OUTPUT_SERVERURL` etc. so that the variable names can be computed automatically from the available setting names.

Let me know if this seems to make sense and lines up with what you have in mind.

**Comment by coderpatros** [comment]
Thanks @nblumhardt

**Comment by nblumhardt** [comment]
Closed in #57
