### ISSUE TITLE
Upgrading from 1.1 to 2.0.3 error installing

### ISSUE THREAD

**Issue by xantari** [datalust/seq-forwarder#59]
I've uninstalled the existing seq forwarder service (1.1) and it is no longer running as a service.

When I did the following command:

./seqfwd.exe install

I got the following errors:

```
PS C:\Program Files\seq-forwarder> .\seqfwd.exe install
Installing service...
Updating the configuration in C:\ProgramData\Seq\Forwarder\SeqForwarder.json...
Granting NT AUTHORITY\LocalService rights to C:\ProgramData\Seq\Forwarder...
Granting NT AUTHORITY\LocalService rights to C:\ProgramData\Seq\Logs\...
Adding URL reservation at http://+:15341/ for NT AUTHORITY\LocalService...

Url reservation add failed, Error: 183
Cannot create a file when that file already exists.


Could not add URL reservation for http://+:15341/: `netsh` returned 1; ignoring
[SC] CreateService SUCCESS
Setting service restart policy...
[SC] ChangeServiceConfig2 SUCCESS
Setting service description...
[SC] ChangeServiceConfig2 SUCCESS
Service installed successfully.
PS C:\Program Files\seq-forwarder>
```

I'm not sure if it's fully installed now or why it didn't work. My guess is the past versions uninstall command didn't fully clean up after itself?

I did the following command:

```
netsh http show urlacl
```

It shows this:

```

   Reserved URL            : http://+:15341/
       User: NT AUTHORITY\LOCAL SERVICE
           Listen: Yes
           Delegate: No
           SDDL: D:(A;;GX;;;LS)
```

My guess is I should be good to go?

**Comment by nblumhardt** [comment]
Hi @xantari - thanks for the heads-up! My understanding is that this is fine; the `install` command should probably be quieter about it - but with the reservation already created, the new forwarder service should be ready to run.

Let us know if you run into any trouble, though!

**Comment by xantari** [comment]
Yep, was in innocuous error. Closing.
