### ISSUE TITLE
Is this deprecated?

### ISSUE THREAD

**Issue by nitewulf** [datalust/seq-forwarder#65]
I found documentation on the datalust site for the forwarder and there was a banner that said the documentation version was out of date.  When clicking to see the 2023.1 version of the documentation, there is no longer any mention of the seq forwarder.

As we update apps to use structured logging we would potentially have dozens of apps/server logging and I thought using the forwarder would be a good idea - if it is still recommended to use.

**Comment by nblumhardt** [comment]
Hi Scott, thanks for dropping us a line. Seq Forwarder is still maintained, but at this point it's only really intended for use in some fairly specific cases (e.g. occasionally-connected devices/networks). Many logging libraries maintain a short in-memory buffer to deal with intermittent connectivity issues in normal use, and this is a more reliable/manageable setup for most people.

If you need a hand figuring out what's best for you, feel free to send some more details to support@datalust.co and we'll dig into it. Hope this helps!
