### ISSUE TITLE
Changes to the target Seq's DNS entry is not detected

### ISSUE THREAD

**Issue by williamb1024** [datalust/seq-forwarder#66]
If the internal HttpClient instance does not idle for a sufficiently long period of time, the DNS name for the Seq instance will never be resolved after the initial resolution.

This causes the forwarder instance to miss changes to the Seq server's IP address if the fowarder remains busy. 

I suggest adding a TimeSpan named PooledConnectionLifetime field in the SeqForwarderOutputConfig. During the registration of the HttpClient instance, use the configured TimeSpan value to set the PooledConnectionLifetime property of the SocketsHttpHandler.

I would be happy to provide a pull request, if you are interested.

**Comment by nblumhardt** [comment]
Hi @williamb1024, thanks for the report, this sounds like a good change. We'd be happy to work through a PR if you are able to send one 👍

**Comment by nblumhardt** [comment]
#67 addressed this
