### ISSUE TITLE
Provide arm64 builds

### ISSUE THREAD

**Issue by ricardoboss** [datalust/seq-forwarder#69]
Hi! I was wondering if you are planning to support linux/arm64 and/or macos/arm64?

For the time being I am able to compile it myself, but it would be nice to be able to just download official relases.

**Comment by nblumhardt** [comment]
Hi @ricardoboss - thanks for getting in touch!

We don't have it on the current schedule but would be happy to accept a PR if you're interested in sending one? AFAIK the required changes should mostly be local to `Build.ps1`, but I'd need to tinker to find out.
